# Generated by Django 5.1.4 on 2025-03-21 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FactorsInDiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factors', models.CharField(max_length=50, unique=True)),
                ('test_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.diagnostictest')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultFactorValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveIntegerField()),
                ('min_age_unit', models.CharField(choices=[('years', 'Years'), ('months', 'Months'), ('days', 'Days')], default='years', max_length=10)),
                ('max_age', models.PositiveIntegerField()),
                ('max_age_unit', models.CharField(choices=[('years', 'Years'), ('months', 'Months'), ('days', 'Days')], default='years', max_length=10)),
                ('min_value', models.PositiveIntegerField(blank=True, null=True)),
                ('max_value', models.PositiveIntegerField(blank=True, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('test_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='default_factors', to='patients.diagnostictest')),
                ('factor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.factorsindiagnostictest')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('referred_doctor', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveIntegerField()),
                ('age_unit', models.CharField(choices=[('years', 'Years'), ('months', 'Months'), ('days', 'Days')], default='years', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tests', models.ManyToManyField(to='patients.diagnostictest')),
            ],
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.diagnostictest')),
            ],
        ),
        migrations.CreateModel(
            name='TestReportResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_value', models.FloatField()),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.factorsindiagnostictest')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='patients.testreport')),
            ],
        ),
    ]
