# Generated by Django 5.2 on 2025-04-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_testreportresult_max_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultfactorvalues',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='defaultfactorvalues',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
